# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Lais Carvalho
title: Student, Events Organiser
email: lais.carvalho@python.ie
website: https://laisbsc.github.io/laiscarvalho.github.io/

# Social links
twitter_username: lais_bsc
github_username:  laisbsc
# dribbble_username: jekyll
# facebook_username: lais-barbara-carvalho
# flickr_username: jekyll
instagram_username: laiscarvalho
linkedin_username: lais-barbara-carvalho
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Lais and I’m a 3rd year IT student in CCT Colege Dublin 
  that fell in love with Python after struggling with Wolfran for 2 years 
  trying to understand advanced calculus. I used to design water dams for least-privileged
  communities in Brazil, before moving to Ireland. With 6 years of experience with customer service,
  I am currently training as a Remote Conference Operator with projects throughout the tech community
  such as Pyjamas and Python Ireland. Aiming to become a DevRel in the nebar future.

  I am most skilled in: <mark>Customer Service</mark> and <mark>Python</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networking and AI some of my other interests include:
   - Aerial Silks
   - Yoga
   - Mindful meditation
   - Wine.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
