# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Lais Carvalho
title: Student, Tech events organiser
email: lais.carvalho@python.ie
website: http://laiscarvalho.com/

#darkmode: false

# Social links
twitter_username: lais_bsc
github_username:  laisbsc
# dribbble_username: jekyll
facebook_username: laisbsc
# stackoverflow_username: jekyll
# flickr_username: jekyll
instagram_username: laiscarvalho
linkedin_username: lais-barbara-carvalho
# dev_username: laisbsc
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Additional icon links
additional_links:
- title: Dev
  icon: fa-dev (https://fontawesome.com/icons/dev?style=brands)
  url: https://dev.to/laisbsc
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I’m a 3rd year IT student at CCT College Dublin that fell in love with Python after struggling 
  with Wolfram for 2 years trying to understand advanced calculus. I used to design water dams for the least-privileged
  communities in Brazil, prior of my move to Ireland. With 6 years of experience with customer service,
  I am currently training as a Remote Conference Operator with projects throughout the tech community, 
  such as Pyjamas and EuroPython.

I am most skilled in: <mark>Customer Service</mark> and <mark>Python</mark>

# Projects Section
# projects_title: Projects

# Portfolio Section
# portfolio_title: Portfolio

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my curiosity about networking and AI, some of my other interests include:
   - Aerial Silks
   - Yoga
   - Mindful meditation and
   - Wine!

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
